### ISSUE TITLE
Close 'emoji-menu-open' when clicking outside

### ISSUE THREAD

**Issue by leephan2k1** [PandaSekh/lepre#261]
I really like your library and I am currently using it for my personal project.

But I need more that when user clicks out of 'emoji-adder' it will change back to 'emoji-menu-closed'
I tried doing it manually using Javascript to call .click() on the emoji. But it seems to conflict with lepre's API

If you have time, check it out
Thanks very much

**Comment by PandaSekh** [comment]
Hi,

Sorry but it's not clear to me what you want to do. Can you please be more specific?

Thanks

**Comment by leephan2k1** [comment]
I want more option 2 like this to close emoji menu

![desc](https://user-images.githubusercontent.com/54581258/199954909-a88288d2-9629-4888-9e8a-f14c236e254c.png)

**Comment by PandaSekh** [comment]
Should be done with `v0.7.0`. I wasn't able to properly test this, if it doesn't work feel free to open a PR and fix it. 
I won't work on this project anymore
